# Pre-commit hooks configuration for Brain Go Brrr
# Philosophy: Fast local hooks (< 2s), strict CI checks
# Developers should never wait more than 2 seconds to commit

repos:
  # Ruff - Fast Python formatter and linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      # Format first - always auto-fix, never block
      - id: ruff-format
        name: ruff format (auto-fix)
        types_or: [python, pyi]
        exclude: ^(reference_repos/|data/|\.venv/|build/|dist/)

      # Lint with only fast, critical rules
      - id: ruff
        name: ruff lint (fast rules only)
        # Only run fast rules that can auto-fix
        args: [
          --fix,
          --select, "I,E,F,W,B,UP",  # imports, errors, pyflakes, warnings, bugbear, pyupgrade
          --ignore, "E501,E712,B008",  # line length, comparison, FastAPI Depends - let CI handle
        ]
        types_or: [python, pyi]
        exclude: ^(reference_repos/|data/|\.venv/|build/|dist/)

  # Type checking - MOVED TO CI for speed
  # Uncomment to enable mypy in pre-commit (adds ~5-10s)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.17.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [pydantic>=2.0, types-requests, numpy]
  #       args: [--ignore-missing-imports, --no-error-summary]
  #       files: ^src/
  #       exclude: ^(reference_repos/|data/|\.venv/|build/|dist/|tests/)

  # Essential file checks - all very fast
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(reference_repos/|data/)
      - id: end-of-file-fixer
        exclude: ^(reference_repos/|data/)
      - id: check-yaml
        exclude: ^reference_repos/  # Exclude external repos
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=10000]  # 10MB limit
      - id: check-merge-conflict
      - id: check-case-conflict

  # Prevent accidental commits of sensitive files
  - repo: local
    hooks:
      - id: check-model-files
        name: check no model files
        entry: 'Model files should not be committed'
        language: fail
        files: \.(pt|pth|h5|ckpt|safetensors)$

      - id: check-data-files
        name: check no large data files
        entry: 'Large data files should use DVC or Git LFS'
        language: fail
        files: \.(csv|parquet|feather|edf)$
        # Allow small test fixtures
        exclude: ^tests/fixtures/.*\.(csv|edf)$

# Configuration
default_language_version:
  python: python3.11

# Don't run on CI - CI has its own strict checks
ci:
  skip: [ruff, ruff-format]  # mypy already disabled above
