# MkDocs configuration for Brain Go Brrr documentation
site_name: Brain Go Brrr
site_description: A digital twin brain-computer interface project focused on EEG signal processing and neural representation learning
site_url: https://clarity-digital-twin.github.io/brain-go-brrr/
repo_url: https://github.com/Clarity-Digital-Twin/brain-go-brrr
repo_name: Clarity-Digital-Twin/brain-go-brrr

# Theme configuration
theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - meta
  - toc:
      permalink: true

# Extra JavaScript for MathJax
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Navigation
nav:
  - Home: PROJECT_STATUS.md
  - Requirements:
      - Product Requirements: requirements/PRD-product-requirements.md
      - Technical Requirements: requirements/TRD-technical-requirements.md
      - Behavior Specifications: requirements/BDD-behavior-specifications.md
  - Technical Documentation:
      - Literature Reference: docs/technical/literature-master-reference.md
      - Technical Stack: docs/technical/tech-stack.md
      - Pipeline Overview: docs/technical/pipeline_overview.md
      - Development Standards: docs/technical/development-standards.md
      - Agentic Workflow: docs/technical/agentic-workflow.md
  - Implementation:
      - Implementation Plan: docs/implementation/IMPLEMENTATION_PLAN.md
      - MVP Summary: docs/implementation/MVP_SUMMARY.md
      - Configuration Checklist: docs/implementation/CONFIGURATION_CHECKLIST.md
      - Testing Best Practices: docs/implementation/TESTING_BEST_PRACTICES.md

# Plugins
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_if_no_docstring: false

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Clarity-Digital-Twin/brain-go-brrr
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/brain-go-brrr/
  version:
    provider: mike
