name: Smoke Test

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoke-test:
    name: Quick Smoke Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          
      - name: Install dependencies
        run: uv sync --all-extras
        
      - name: Run import checks
        run: |
          uv run python -c "
          print('Testing critical imports...')
          import numpy as np
          import torch
          import pytorch_lightning
          import sklearn.metrics
          from brain_go_brrr.data.tuab_dataset import TUABDataset
          from brain_go_brrr.tasks.abnormality_detection import AbnormalityDetectionProbe
          print('✅ All imports successful!')
          "